### ISSUE TITLE
Cannot pull: asks for user name and password

### ISSUE THREAD

**Issue by Audioniek** [OpenVisionE2/servicemp3epl#1]
See title; build process becomes interactive.

**Comment by MastaG** [comment]
Hi Nico, je hebt nu schrijf toegang hoor...

git clone https://github.com/OpenVisionE2/servicemp3epl.git

Zou trouwens zoiezo moeten werken.

Lees ook even goed wat ik hier schreef: https://github.com/OpenVisionE2/servicemp3epl/commit/986e6f7438dbd6d9a1077209d6804685f15987a3#commitcomment-32087452
